USE assignment2
INSERT INTO Users (name, gender, date_of_birth) values ("aHEfvq7WLIDMvt", "F", "2009-4-23");
INSERT INTO Users (name, gender, date_of_birth) values ("ER88IyIe7X32iwO", "F", "2008-6-15");
INSERT INTO Users (name, gender, date_of_birth) values ("wXRplGufV15C9ja8Df", "F", "2017-4-5");
INSERT INTO Users (name, gender, date_of_birth) values ("A0qs1Uva3tZeS7x3", "M", "2017-9-22");
INSERT INTO Users (name, gender, date_of_birth) values ("WSLN8YgA2c0O", "F", "2013-12-5");
INSERT INTO Users (name, gender, date_of_birth) values ("R23heqtWIBjbbvxbsGEm", "F", "2020-12-18");
INSERT INTO Users (name, gender, date_of_birth) values ("S3Ow4LIwHf", "F", "2014-11-16");
INSERT INTO Users (name, gender, date_of_birth) values ("VUJPWG5Pjt1LvpsY", "F", "2025-10-11");
INSERT INTO Users (name, gender, date_of_birth) values ("rkAm6Ou7KCQD", "M", "2019-6-16");
INSERT INTO Users (name, gender, date_of_birth) values ("fwjkgXc6mTJo", "M", "2022-9-20");
INSERT INTO Friendships (user_id, friend_id) values (1,10);
INSERT INTO Friendships (user_id, friend_id) values (1,9);
INSERT INTO Friendships (user_id, friend_id) values (1,7);
INSERT INTO Friendships (user_id, friend_id) values (9,4);
INSERT INTO Friendships (user_id, friend_id) values (6,6);
INSERT INTO Friendships (user_id, friend_id) values (3,10);
INSERT INTO Friendships (user_id, friend_id) values (4,8);
INSERT INTO Friendships (user_id, friend_id) values (2,1);
INSERT INTO Friendships (user_id, friend_id) values (8,2);
INSERT INTO Friendships (user_id, friend_id) values (2,8);
INSERT INTO Friendships (user_id, friend_id) values (7,10);
INSERT INTO Friendships (user_id, friend_id) values (4,6);
INSERT INTO Friendships (user_id, friend_id) values (3,1);
INSERT INTO Friendships (user_id, friend_id) values (4,8);
INSERT INTO Friendships (user_id, friend_id) values (10,10);
INSERT INTO Friendships (user_id, friend_id) values (3,1);
INSERT INTO Friendships (user_id, friend_id) values (1,5);
INSERT INTO Friendships (user_id, friend_id) values (10,8);
INSERT INTO Friendships (user_id, friend_id) values (8,7);
INSERT INTO Friendships (user_id, friend_id) values (8,9);
INSERT INTO Friendships (user_id, friend_id) values (5,4);
INSERT INTO Friendships (user_id, friend_id) values (7,1);
INSERT INTO Friendships (user_id, friend_id) values (10,4);
INSERT INTO Friendships (user_id, friend_id) values (4,6);
INSERT INTO Friendships (user_id, friend_id) values (6,3);
INSERT INTO Posts (user_id, text) values (10, "VmnRzcBmtno6jV7igf");
INSERT INTO Posts (user_id, text) values (9, "9M594mglua");
INSERT INTO Posts (user_id, text) values (1, "jqAgS7Sw2j");
INSERT INTO Posts (user_id, text) values (5, "GxCN0Vc7bOrfqUv6VFvM");
INSERT INTO Posts (user_id, text) values (3, "0l2PuEhSPh9Vuaqfp");
INSERT INTO Posts (user_id, text) values (7, "FbNFvo047gYL8FQYWpK");
INSERT INTO Posts (user_id, text) values (5, "4ER0rlrCANej");
INSERT INTO Posts (user_id, text) values (10, "VgpqUTVdToGjRQRoa8r");
INSERT INTO Posts (user_id, text) values (8, "3HV0AzndzqWZ");
INSERT INTO Posts (user_id, text) values (1, "HfhLXnqOyzw4ARQDoOVu");
INSERT INTO Posts (user_id, text) values (1, "5F1UuUjGUhFf2YmD7");
INSERT INTO Posts (user_id, text) values (9, "ArkGoexw8c4jeojxA");
INSERT INTO Posts (user_id, text) values (9, "ZHKKpWt5XU5ihY8yf5T");
INSERT INTO Posts (user_id, text) values (5, "LylifEQ2RHSqFsSv6");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 1, "kVOz9jdFapVNqJDht");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 3, "E0Ot4ME4TNELgNvEvA");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 5, "TJMfUlxSmxOlmGRr6hXP");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 4, "auJGzfaPOab6VqBs4");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 1, "tetlr0axjrZzPqTBw");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 4, "NP23VwMMIfxwqBHBccm");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 8, "PONSPL2Xjsexyzu1jtc1");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 2, "9jRABTQcmz");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 3, "MEMQyqmQ3CQ");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 10, "tlNeLTWqICm");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 5, "ssMGCZAsKL");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 8, "H2303RwDLGzxJgEB8B7");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 4, "gc2PLSuPh5r11U");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 1, "Ny46pgbmkFo");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 7, "o6YDj5MFscAWzmc");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 8, "IZkx9hmbKzevMEKWVDU");
INSERT INTO Comments (post_id, commenter_user_id, text) values (14, 2, "5iy3beiJLDI9toEY");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 8, "J31VOc4UTKMwe436q");
INSERT INTO Comments (post_id, commenter_user_id, text) values (6, 6, "f2T8n2zHTZNhh9w");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 8, "fvkj3HBnMV");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 7, "QxPlelTDwhHA659");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 7, "tC5aC8y9zj1FBj2");
INSERT INTO Comments (post_id, commenter_user_id, text) values (8, 7, "AfjcTjru7RDCgNEdNhVy");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 1, "lk2PwIYdNz");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 6, "h0mRK8uYintaup");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 5, "kWsqvuTjtga");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 9, "xHBqksujFR1XyHIMXP6");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 5, "MPTjNwUtIR");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 3, "nLPCftoOyro4diE");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 10, "fOb8qTdAVBl0JT7qdS3M");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 3, "M7yeIEnRUfuUqnmMQt2k");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 9, "NZJsVefxrUipocZEWo5");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 8, "5EaKcY431rmOqBHyiRO");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 4, "OEbxkCvzhM7cTDcJ9sJI");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 10, "c8gQcNG2vYZTOjvku");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 10, "ltdJISJLBG5V8zkmU");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 10, "qOUal0NkX4raxF5KP0");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 10, "Te8x8PwasMLENYWs");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 4, "5VnlQtGCwwIRP4qeEg");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 9, "Z4t8fcqmcP5");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 5, "HbtHzQCz4KaNLhWWL5g");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 5, "OH2E3h8Blabb9jVN7O");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 9, "SS3UTI0wMbU");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 6, "ZBO8AKfdr0c3g");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 7, "QiamY1poe3a5yRs");
INSERT INTO Comments (post_id, commenter_user_id, text) values (14, 3, "h98wGHdvgITQBVw59r");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 5, "uF2qXBxufInJDipS");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 8, "rdeZuSW04ZwQuZPPiaF");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 9, "Tgmb7aaMDXSx5Xy");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 2, "tU5IEjN76ou");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 4, "86aEZGm6Jv5RHwofp");
INSERT INTO Comments (post_id, commenter_user_id, text) values (8, 9, "fyCUI5XfvoM");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 5, "Y8rWjUuUdBA4IKdw1");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 5, "a097q6X6I54gPd9MV");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 9, "YzzMZIhbduyLYQb9v");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 5, "5vRATPrExzsk0YrNJdl");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 5, "znuDIIyPFjjDI33vZ");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 7, "zcgl60S3F1YuvikO6Zkf");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 2, "Ci67YtoQATF0LEEatlm");
INSERT INTO Comments (post_id, commenter_user_id, text) values (6, 2, "wWCfKyUqq0Apr4i1lO");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 10, "qggjdYVOwt7txZY8n");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 4, "3UF5fvkNzyPn");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 5, "8fRgyxO2xWmstpvGkSCh");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 4, "GVEXTcPpuGG");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 2, "x4CYIne6VKIZmAR");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 5, "nk72haQp33OZ6p");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 7, "YSIkgpOzEmB");
INSERT INTO Comments (post_id, commenter_user_id, text) values (8, 2, "5lbWAv1xvpilQZEMYcw");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 6, "nl86XWPnvUtrCx0aqde");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 2, "PTBZraKTzekg7OjQ2LW");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 7, "t6nqpSRM6jCcr89Cd0m");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 6, "AhjZEukVJM2xc5GyZJv");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 4, "PHrvhErcfBswZijQO4St");
INSERT INTO Comments (post_id, commenter_user_id, text) values (6, 4, "uJh65pmx5iJ");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 9, "U2Zav8t4M4dh802C4JlQ");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 5, "MkGixlbjHko");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 1, "dxkWdxGvyog7jD");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 3, "rvBBovmv4kiGeqCvIi");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 5, "9IdZYmOOp0XEgNPF0AJ");
INSERT INTO Comments (post_id, commenter_user_id, text) values (6, 10, "a0O0t3VDVQn5TAqKXb6j");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 9, "LdV7I0u3Pa");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 1, "QfAMopYRjsrHi7Gl25R");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 1, "H4TU7eefMWu0YOjNYKp");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 6, "BIhpX2Ame5H");
INSERT INTO Comments (post_id, commenter_user_id, text) values (8, 3, "8pV5bvY4lqs8ovhCI");
INSERT INTO Comments (post_id, commenter_user_id, text) values (8, 8, "px41y5r55o86VLhm");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 7, "Xzc7sv39LOdr62Hqzq5A");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 4, "ZMhZDNfK3l7K9D");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 6, "KzqfX6YSObLD4xE9fo9");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 6, "qk2MIkSWtfnIk6tMJ");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 8, "6NXjII3Po7");
INSERT INTO Comments (post_id, commenter_user_id, text) values (14, 2, "uG9DdRf6GuCEjln");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 1, "JsOecNZzoq");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 1, "K4ahYwz0bK9A");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 5, "W5bQabZUuTn");
INSERT INTO Comments (post_id, commenter_user_id, text) values (6, 3, "BIs8w45kE47URL1f4");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 7, "O8tpVTtq0gXr");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 9, "t4urCltgVRHGWs72Vm");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 6, "mNxEEpqgdFdh3");
INSERT INTO Comments (post_id, commenter_user_id, text) values (14, 10, "XTW7hNPcEM");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 1, "A3vcQY8aaiLZrEW7cD");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 2, "eQ7omzvu58tth8JxuZVU");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 8, "FfhPUxau0wq0plaGP8");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 4, "SfSA5o2vr2f1CHnlQ8Po");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 2, "YQl5MrM5rLe");
INSERT INTO Comments (post_id, commenter_user_id, text) values (8, 3, "rmKCOFVwt42qrbB");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 5, "2NiBlJRdV0CjMJz1y");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 3, "CCnBiJz6cK3");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 10, "NJvMYNcjauEXfAg1Azx");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 5, "lkJN7o0hwsOmiYNnfa");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 10, "jCu90BvJ5ByMzH");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 6, "oOWqr34F1lndTSufs5b6");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 8, "uTk6RhU6mqKR4Ai9W4pe");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 6, "w8uRnRKILH");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 10, "r1LU8Nqp3nrcO79KOw");
INSERT INTO Comments (post_id, commenter_user_id, text) values (2, 3, "CkXE8AujVtCW");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 5, "shd3wBj17jG");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 3, "57VgCmRREUp");
INSERT INTO Comments (post_id, commenter_user_id, text) values (11, 10, "mOsfp1MOyxXFKaCg3");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 10, "1HuKPZQP65ZN");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 8, "NqQ3NXRheyzi");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 2, "6MCXsvBn2iqQnJF3oMVL");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 10, "1vgWFBVhnlb");
INSERT INTO Comments (post_id, commenter_user_id, text) values (13, 9, "O18mfB1PFGNjV38D");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 5, "v520fE6D2Fgalh3");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 1, "ID34UaWk2p");
INSERT INTO Comments (post_id, commenter_user_id, text) values (4, 10, "k6YK0Ah8z3nOUkMKyh");
INSERT INTO Comments (post_id, commenter_user_id, text) values (3, 1, "TUkyRWLJnoWzx8");
INSERT INTO Comments (post_id, commenter_user_id, text) values (1, 1, "Xkrt8Dozc6bvb5");
INSERT INTO Comments (post_id, commenter_user_id, text) values (6, 3, "7mommeb7Ptikjmh1h");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 2, "4EYvFQrCXUb9RJcJki");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 6, "URubRFtvlq2");
INSERT INTO Comments (post_id, commenter_user_id, text) values (14, 8, "jXTY6VzVqNJ6XDy");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 3, "PL0XYXrCGy");
INSERT INTO Comments (post_id, commenter_user_id, text) values (9, 3, "P9LcvsfFSrax7O");
INSERT INTO Comments (post_id, commenter_user_id, text) values (10, 3, "jm1X5xfwh29JGLM");
INSERT INTO Comments (post_id, commenter_user_id, text) values (14, 5, "13nJLFIdJMmWqaVVmwa");
INSERT INTO Comments (post_id, commenter_user_id, text) values (5, 4, "7sGAbaIyF3LV");
INSERT INTO Comments (post_id, commenter_user_id, text) values (12, 2, "KpycuS5NyUW");
INSERT INTO Comments (post_id, commenter_user_id, text) values (7, 5, "XvJIDgnFEwE");
