SELECT POSTS.USER_ID FROM 
COMMENTS  LEFT JOIN POSTS 
on COMMENTS.POST_ID=5 AND COMMENTS.COMMENTER_USER_ID  = POSTS.USER_ID;



Query1

INSERT INTO USERS (name, gender, date_of_birth) values ("answer1", "M", "2020-10-21");
INSERT INTO COMMENTS (POST_ID, COMMENTER_USER_ID , text) values (5, 1001, "smnhovltskzajqybxjgw");

SELECT DISTINCT USERS.USER_ID, USERS.NAME FROM
	(SELECT candidates.COMMENTER_USER_ID  FROM 
	(SELECT COMMENTER_USER_ID  from COMMENTS WHERE POST_ID=5) candidates 
	LEFT JOIN POSTS ON candidates.COMMENTER_USER_ID  = POSTS.USER_ID
	WHERE POSTS.USER_ID is null) first
	JOIN
	USERS
	WHERE USERS.USER_ID=first.COMMENTER_USER_ID ;



Query2

INSERT INTO FRIENDSHIPS (USER_ID, FRIEND_ID) VALUES (1,169);
INSERT INTO FRIENDSHIPS (USER_ID, FRIEND_ID) VALUES (1,85);
INSERT INTO FRIENDSHIPS (USER_ID, FRIEND_ID) VALUES (1,778);
INSERT INTO FRIENDSHIPS (USER_ID, FRIEND_ID) VALUES (1,968);


SELECT first.FRIEND_ID FROM
(SELECT candidates.FRIEND_ID FROM
(SELECT FRIEND_ID FROM FRIENDSHIPS WHERE USER_ID=1) candidates
JOIN USERS
ON 
candidates.FRIEND_ID=USERS.USER_ID AND USERS.GENDER="F") first
JOIN
(SELECT FRIEND_ID FROM FRIENDSHIPS WHERE USER_ID=2) second
ON first.FRIEND_ID=second.FRIEND_ID;




Query3


SELECT candidates.USER_ID FROM
(SELECT USER_ID FROM FRIENDSHIPS
GROUP BY USER_ID
HAVING COUNT(FRIEND_ID) > 2) candidates
JOIN
(SELECT USERS.USER_ID FROM USERS 
JOIN POSTS
ON USERS.USER_ID=POSTS.USER_ID
GROUP BY USERS.USER_ID
HAVING COUNT(POST_ID) > 1) postcandidates
ON candidates.USER_ID=postcandidates.USER_ID;




Query4

use unique since repeated USERS might exist




SELECT FRIENDSHIPS.USER_ID as USER_ID, COUNT(FRIENDSHIPS.FRIEND_ID) as count FROM
(SELECT femaleusers.USER_ID FROM
(SELECT USER_ID FROM USERS WHERE USERS.gender="F" AND USERS.date_of_birth>"19901220") femaleusers
JOIN COMMENTS
ON COMMENTS.POST_ID=10 AND COMMENTS.COMMENTER_USER_ID =femaleusers.USER_ID) candidates
JOIN FRIENDSHIPS
ON 	candidates.USER_ID=FRIENDSHIPS.USER_ID
GROUP BY FRIENDSHIPS.USER_ID;



Query5


INSERT INTO COMMENTS (POST_ID, COMMENTER_USER_ID , text) values (7, 227, "kVOz9jdFapVNqJDht");


SELECT FRIEND_ID FROM 
POSTS JOIN FRIENDSHIPS
ON POSTS.POST_ID=7 AND POSTS.USER_ID=FRIENDSHIPS.USER_ID
JOIN COMMENTS
ON COMMENTS.POST_ID=7 and FRIENDSHIPS.FRIEND_ID=COMMENTS.COMMENTER_USER_ID ;



