USE assignment2

DROP TABLE COMMENTS;
DROP TABLE FRIENDSHIPS;
DROP TABLE POSTS;
DROP TABLE USERS;





CREATE TABLE USERS ( 
  USER_ID BIGINT AUTO_INCREMENT NOT NULL, 
  NAME VARCHAR(30),
  GENDER CHAR(1),
  DATE_OF_BIRTH DATE,
  PRIMARY KEY (USER_ID)
  );

CREATE TABLE FRIENDSHIPS(
  USER_ID BIGINT NOT NULL,
  FRIEND_ID BIGINT NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY(FRIEND_ID) REFERENCES USERS(USER_ID)
); 


CREATE TABLE POSTS(
  POST_ID BIGINT AUTO_INCREMENT NOT NULL,
  USER_ID BIGINT,
  TEXT VARCHAR(100),
  PRIMARY KEY(POST_ID),
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
  );

CREATE TABLE COMMENTS(
  COMMENT_ID BIGINT AUTO_INCREMENT NOT NULL,
  POST_ID BIGINT,
  COMMENTER_USER_ID BIGINT,
  TEXT VARCHAR(100),
  PRIMARY KEY(COMMENT_ID),
  FOREIGN KEY(POST_ID) REFERENCES POSTS(POST_ID),
  FOREIGN KEY(COMMENTER_USER_ID) REFERENCES USERS(USER_ID) 
);


